version: "3.3"
services:
    api:
        image: node:16
        volumes:
            - ./:/home/node/app
        user: node
        working_dir: /home/node/app/
        command: "npm start"
        ports:
            - 80:3000
